version: '3.7'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    container_name: "mysqldb"
    environment:
      MYSQL_DATABASE: 'test'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:3000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    environment:
      DATABASE_URL: ${TYPEORM_URL}
      TYPEORM_MIGRATIONS: dist/migration/*.js
    depends_on:
      - mysqldb
  

