version: '3.7'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    container_name: "mysqldb"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${DB_PORT}:3306
      - 9929:9929
    expose:
      # Opens port 3306 on the container
      - '${DB_PORT}'
      # Where our data will be persisted
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    depends_on:
      - mysqldb
  

